import Head from 'next/head';
import { Inter } from 'next/font/google';
import Nav from '@/Components/Nav';
import About from '@/Components/About';
import Experience from '@/Components/Experience';
import Education from '@/Components/Education';
import Courses from '@/Components/Courses';
import Skills from '@/Components/Skills';
import Interests from '@/Components/Interests';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfólio JM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
      </Head>
      <Nav />
      <div class="container-fluid p-0">
        <About />
        <Experience />
        <Education />
        <Courses />
        <Skills />
        <Interests />
      </div>
    </>
  )
}